### ISSUE TITLE
IDEA shows me several clock at once

### ISSUE THREAD

**Issue by alexanderfefelov** [xamgore/intellij-clock#1]
![clocks](https://user-images.githubusercontent.com/5790321/52399559-b4b60200-2acd-11e9-9ff9-0c004007ea63.png)

All clocks are fully functional.

Environment:

Clock Widget v1.0.1
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by alexanderfefelov** [comment]
Yeah! Find out how to reproduce this bug:

* Open any project
* File -> Open recent -> Any project

Another clock appeared in the IDEA status bar.

![1](https://user-images.githubusercontent.com/5790321/52517480-e4d7df00-2c4c-11e9-8883-5cd5ccbf7b45.png)

**Comment by xamgore** [comment]
Well, that's great, thank you! You are welcome to PR, or wait a bit, I'll fix it myself.

**Comment by alexanderfefelov** [comment]
Any news?

**Comment by alexanderfefelov** [comment]
Uninstall.

**Comment by xamgore** [comment]
@alexanderfefelov could you change the rating on [the reviews page](https://plugins.jetbrains.com/plugin/11252-clock-widget/reviews) if you think the problem is solved then?
